# Generated by Django 5.1.15 on 2026-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phoneme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "symbol",
                    models.CharField(
                        help_text="The phoneme symbol, e.g., 'sh', 'ch', 'a_e'", max_length=10, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("single_letter", "Single Letter Sound"),
                            ("digraph", "Digraph"),
                            ("blend", "Blend"),
                            ("long_vowel", "Long Vowel Pattern"),
                            ("r_controlled", "R-Controlled Vowel"),
                            ("diphthong", "Diphthong"),
                        ],
                        db_index=True,
                        help_text="Phonics category this phoneme belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "example_words",
                    models.JSONField(
                        default=list, help_text="List of example words containing this phoneme, e.g., ['ship', 'shop']"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional pre-recorded audio file for this phoneme",
                        null=True,
                        upload_to="phonics/audio/",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Order for display within a category (lower = first)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Phoneme",
                "verbose_name_plural": "Phonemes",
                "ordering": ["category", "display_order", "symbol"],
            },
        ),
    ]
