# Generated by Django 5.1.15 on 2026-04-07 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("phonics", "0002_seed_phonemes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Display name of the game", max_length=100)),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("sound_picture", "Sound → Picture Matching"),
                            ("beginning_sound", "Beginning Sound Selection"),
                            ("blend_builder", "Blend Builder"),
                            ("balloon_pop", "Balloon Pop"),
                        ],
                        help_text="Type/mechanic of the game",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description of the game for display")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Whether this game is available for play"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GamePhonemeMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="phoneme_mappings", to="games.game"
                    ),
                ),
                (
                    "phoneme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_mappings", to="phonics.phoneme"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game-Phoneme Mapping",
                "verbose_name_plural": "Game-Phoneme Mappings",
                "unique_together": {("game", "phoneme")},
            },
        ),
        migrations.AddField(
            model_name="game",
            name="phonemes",
            field=models.ManyToManyField(
                help_text="Phonemes this game supports",
                related_name="games",
                through="games.GamePhonemeMapping",
                to="phonics.phoneme",
            ),
        ),
    ]
