# Generated by Django 5.1.15 on 2026-04-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_seed_games'),
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turns', models.JSONField(default=list, help_text='List of story turns: [{"role": "child"|"llm", "text": "..."}]')),
                ('max_rounds', models.PositiveIntegerField(default=4, help_text='Maximum number of child turns allowed')),
                ('is_complete', models.BooleanField(default=False, help_text='Whether the story has been completed')),
                ('summary', models.TextField(blank=True, help_text='LLM-generated summary of the completed story')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='The learning session this story belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='story_sessions', to='learning_sessions.learningsession')),
            ],
            options={
                'verbose_name': 'Story Session',
                'verbose_name_plural': 'Story Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
