# Generated by Django 5.1.15 on 2026-04-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_seed_story_builder_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysession',
            name='browser_session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Django session key of the browser that created this story', max_length=40),
        ),
    ]
