# Generated by Django 5.1.15 on 2026-04-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this template, e.g., 'phonics_feedback'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="System-level prompt defining the AI tutor's behavior and constraints"),
                ),
                (
                    "user_template",
                    models.TextField(
                        help_text="User message template with placeholders: {phoneme}, {confidence}, {error}, {attempts}"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Whether this template is currently in use"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, help_text="Version number for tracking template changes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt Template",
                "verbose_name_plural": "Prompt Templates",
                "ordering": ["-is_active", "-version"],
            },
        ),
    ]
