# Generated by Django 5.1.15 on 2026-04-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tutor", "0002_seed_default_prompts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompttemplate",
            name="name",
            field=models.CharField(help_text="Identifier for this template, e.g., 'phonics_feedback'", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="prompttemplate",
            unique_together={("name", "version")},
        ),
    ]
