# Generated by Django 5.1.15 on 2026-04-07 03:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("phonics", "0002_seed_phonemes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Auto-generated anonymous session identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, help_text="When the session was created")),
                (
                    "last_active_at",
                    models.DateTimeField(auto_now=True, help_text="Last activity timestamp (auto-updated on save)"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, help_text="Whether this session is still active"),
                ),
                (
                    "current_phoneme",
                    models.ForeignKey(
                        blank=True,
                        help_text="The phoneme the child is currently working on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_sessions",
                        to="phonics.phoneme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Session",
                "verbose_name_plural": "Learning Sessions",
                "ordering": ["-started_at"],
            },
        ),
    ]
