# Generated by Django 5.1.15 on 2026-04-07 03:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning_sessions", "0001_initial"),
        ("phonics", "0002_seed_phonemes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeechAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Speech recognition confidence score (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "detected_error",
                    models.CharField(
                        blank=True,
                        help_text="Detected substitution error, e.g., '/s/' for '/sh/'",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(help_text="Sequential attempt number for this phoneme in this session"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this attempt was recorded")),
                (
                    "phoneme",
                    models.ForeignKey(
                        help_text="The phoneme that was being practiced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speech_attempts",
                        to="phonics.phoneme",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The learning session this attempt belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speech_attempts",
                        to="learning_sessions.learningsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Speech Attempt",
                "verbose_name_plural": "Speech Attempts",
                "ordering": ["session", "phoneme", "attempt_number"],
                "indexes": [models.Index(fields=["session", "phoneme"], name="idx_attempt_session_phoneme")],
            },
        ),
    ]
